version: '3.9'

services:

  contactsprocessor:
    image: contactsprocessor
    hostname: contactsprocessor
    container_name: contactsprocessor
    ports:
      - "8080:8080"
    restart: always
    networks:
      - contacts-network
    depends_on:
      contacts
      contactsprocessor_db:
          condition: service_healthy
    env_file:
      - .env_contactsprocessor

  contactsprocessor_db:
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - "3000:5432"
    env_file:
      - ./.env_postgres
    networks:
      - contacts-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - contactsprocessor_db:/var/lib/postgresql/data

networks:
  contacts-network:

volumes:
  contactsprocessor_db:
    driver: local